export const db_buro = [
  {
    id: 1,
    tipo_id: "CÉDULA",
    no_identif: "101230456",
    cantidad_referencias_comerciales: "0",
    monto_referencias_comerciales: "₡1000",
    cantidad_juicios_activos: "0",
    monto_juicios_activos: "₡25000",
    cantidad_embargo_muebles: "0",
    monto_embargo_muebles: "₡35000",
    cantidad_embargo_inmuebles: "0",
    monto_embargo_inmuebles: "₡0",
    cantidad_juicios_historicos: "0",
    monto_juicios_historicos: "₡7000",
    cantidad_referencias_comerciales_hist: "0",
    monto_referencias_comerciales_hist: "₡13,000",
    cantidad_bienes_prendados: "0",
    monto_bienes_prendados: "₡35000",
    cantidad_bienes_hipotecados: "0",
    montos_bienes_hipotecados: "₡0",
    meses_salario: "0",
    salario_promedio: "₡0",
    empresa: "NA",
    meses_impuestos: "12",
    impuesto_promedio: "₡121000",
    empresa_2: "RESTAURANTE BRISAS",
    endidad: "GOLLO",
    tipo_operacion: "NA",
    saldo_actual: "₡178000",
    cuota_mensual: "₡7500",
    tasa: "35%",
    condicion: "DEUDOR"
  },
  {
    id: 2,
    tipo_id: "CÉDULA",
    no_identif: "157203450678",
    cantidad_referencias_comerciales: "0",
    monto_referencias_comerciales: "₡50,000",
    cantidad_juicios_activos: "1",
    monto_juicios_activos: "₡50,000",
    cantidad_embargo_muebles: "1",
    monto_embargo_muebles: "₡50,000",
    cantidad_embargo_inmuebles: "1",
    monto_embargo_inmuebles: "₡50,000",
    cantidad_juicios_historicos: "1",
    monto_juicios_historicos: "₡50,000",
    cantidad_referencias_comerciales_hist: "1",
    monto_referencias_comerciales_hist: "₡50,000",
    cantidad_bienes_prendados: "1",
    monto_bienes_prendados: "₡50,000",
    cantidad_bienes_hipotecados: "1",
    montos_bienes_hipotecados: "₡50,000",
    meses_salario: "0",
    salario_promedio: "0",
    empresa: "NA",
    meses_impuestos: "24",
    impuesto_promedio: "₡175000",
    empresa_2: "LOS PATITOS",
    endidad: "IMP MONGE",
    tipo_operacion: "NA",
    saldo_actual: "₡479000",
    cuota_mensual: "₡47000",
    tasa: "34%",
    condicion: "DEUDOR"
  },
  {
    id: 3,
    tipo_id: "CÉDULA",
    no_identif: "304560789",
    cantidad_referencias_comerciales: "1",
    monto_referencias_comerciales: "₡10,000",
    cantidad_juicios_activos: "2",
    monto_juicios_activos: "₡10,000",
    cantidad_embargo_muebles: "2",
    monto_embargo_muebles: "₡10,000",
    cantidad_embargo_inmuebles: "1",
    monto_embargo_inmuebles: "₡10,000",
    cantidad_juicios_historicos: "1",
    monto_juicios_historicos: "₡10,000",
    cantidad_referencias_comerciales_hist: "1",
    monto_referencias_comerciales_hist: "₡10,000",
    cantidad_bienes_prendados: "2",
    monto_bienes_prendados: "₡10,000",
    cantidad_bienes_hipotecados: "1",
    montos_bienes_hipotecados: "₡10,000",
    meses_salario: "0",
    salario_promedio: "0",
    empresa: "NA",
    meses_impuestos: "36",
    impuesto_promedio: "₡75000",
    empresa_2: "LOS CHANCHITOS",
    endidad: "ICE TELEC",
    tipo_operacion: "NA",
    saldo_actual: "₡55000",
    cuota_mensual: "₡15000",
    tasa: "35%",
    condicion: "DEUDOR"
  },
  {
    id: 4,
    tipo_id: "CÉDULA",
    no_identif: "3101787856",
    cantidad_referencias_comerciales: "3",
    monto_referencias_comerciales: "₡13,000",
    cantidad_juicios_activos: "1",
    monto_juicios_activos: "₡13,000",
    cantidad_embargo_muebles: "1",
    monto_embargo_muebles: "₡13,000",
    cantidad_embargo_inmuebles: "1",
    monto_embargo_inmuebles: "₡13,000",
    cantidad_juicios_historicos: "1",
    monto_juicios_historicos: "₡13,000",
    cantidad_referencias_comerciales_hist: "1",
    monto_referencias_comerciales_hist: "₡13,000",
    cantidad_bienes_prendados: "1",
    monto_bienes_prendados: "₡13,000",
    cantidad_bienes_hipotecados: "1",
    montos_bienes_hipotecados: "₡13,000",
    meses_salario: "0",
    salario_promedio: "0",
    empresa: "NA",
    meses_impuestos: "48",
    impuesto_promedio: "₡1100,000",
    empresa_2: "LOS PERRITOS",
    endidad: "CLARO",
    tipo_operacion: "NA",
    saldo_actual: "₡27000",
    cuota_mensual: "₡9500",
    tasa: "36%",
    condicion: "DEUDOR"
  }
]