export const db_cic = [
  {
    id: 1,
    tipo_id: "CÉDULA",
    no_identif: "101230456",
    nombre_completo: "JUAN PEREZ MARÍN",
    entidad: "BAC SAN JOSÉ",
    tipo_operacion: "1",
    saldo_credito: "₡7500000",
    cuota_mensual: "₡125000",
    tasa: "19%",
    condicion: "DEUDOR",
    nivel_chp: "1",
    puntaje: "1.15",
    dias_atraso_max: "25",
    nivel_chp_sbd: "1",
    puntaje_sbd: "1.15",
    dias_atraso_max_sbd: "0",
    operacions_con_estado_1: "0",
    meses_contados: "13"
  },
  {
    id: 2,
    tipo_id: "DIMEX",
    no_identif: "157203450678",
    nombre_completo: "CARLOS DIAS",
    entidad: "BNCR",
    tipo_operacion: "1",
    saldo_credito: "₡22570890",
    cuota_mensual: "₡300000",
    tasa: "7%",
    condicion: "DEUDOR",
    nivel_chp: "2",
    puntaje: "1.85",
    dias_atraso_max: "65",
    nivel_chp_sbd: "0",
    puntaje_sbd: "0",
    dias_atraso_max_sbd: "0",
    operacions_con_estado_1: "1",
    meses_contados: "12"
  },
  {
    id: 3,
    tipo_id: "PASAPORTE",
    no_identif: "304560789",
    nombre_completo: "HUGO CASTRO",
    entidad: "COOPENAE",
    tipo_operacion: "1",
    saldo_credito: "₡11545700",
    cuota_mensual: "₡210000",
    tasa: "12%",
    condicion: "DEUDOR",
    nivel_chp: "3",
    puntaje: "2.50",
    dias_atraso_max: "95",
    nivel_chp_sbd: "0",
    puntaje_sbd: "0",
    dias_atraso_max_sbd: "0",
    operacions_con_estado_1: "2",
    meses_contados: "24"
  },
  {
    id: 4,
    tipo_id: "CÉDULA JURÍDICA",
    no_identif: "3101787856",
    nombre_completo: "ALLAN BONILLA",
    entidad: "B LAFISE",
    tipo_operacion: "3",
    saldo_credito: "₡5975000",
    cuota_mensual: "₡250000",
    tasa: "35%",
    condicion: "DEUDOR",
    nivel_chp: "4",
    puntaje: "3.00",
    dias_atraso_max: "125",
    nivel_chp_sbd: "0",
    puntaje_sbd: "0",
    dias_atraso_max_sbd: "0",
    operacions_con_estado_1: "3",
    meses_contados: "24"
  }
]