export const db_interna = [
  {
    id: 1,
    tipo_id: "CÉDULA",
    no_identif: "101230456",
    codigo_cleinte: "0",
    nombre_completo: "JUAN PEREZ MARÍN",
    tel_trab: "22345678",
    tel_cel: "88885555",
    email: "personal@gmail.com",
    riesgo_cumplimiento: "SI TIENE",
    score_atraso: "NA",
    rango_atraso: "0",
    dias_atraso_max: "0",
    prorrogas_aplicadas: "NA",
    nivel_riesgo: "NA",
    categoria_riesgo: "NA",
    gtia: "AUTOAVAL",
    tipo_oper: "PERSONAL",
    saldo_credito: "₡5700890",
    cuota: "₡125000",
    tasa: "19%",
    condicion: "DEUDOR"
  },
  {
    id: 2,
    tipo_id: "DIMEX",
    no_identif: "157203450678",
    codigo_cleinte: "0",
    nombre_completo: "CARLOS DIAZ SOTO",
    tel_trab: "22837456",
    tel_cel: "87875454",
    email: "personal@gmail.com",
    riesgo_cumplimiento: "NA",
    score_atraso: "NA",
    rango_atraso: "1 A 30",
    dias_atraso_max: "25",
    prorrogas_aplicadas: "NA",
    nivel_riesgo: "NA",
    categoria_riesgo: "NA",
    gtia: "HIPOTECARIA",
    tipo_oper: "VIVIENDA",
    saldo_credito: "₡24,575,700",
    cuota: "₡360,000",
    tasa: "8%",
    condicion: "DEUDOR"
  },
  {
    id: 3,
    tipo_id: "PASAPORTE",
    no_identif: "304560789",
    codigo_cleinte: "0",
    nombre_completo: "HUGO CASTRO BRENES",
    tel_trab: "22445577",
    tel_cel: "85854747",
    email: "personal@gmail.com",
    riesgo_cumplimiento: "NA",
    score_atraso: "NA",
    rango_atraso: "31 A 60",
    dias_atraso_max: "35",
    prorrogas_aplicadas: "NA",
    nivel_riesgo: "NA",
    categoria_riesgo: "NA",
    gtia: "PRENDA",
    tipo_oper: "VEHÍCULO",
    saldo_credito: "₡13,870,234",
    cuota: "₡252,000",
    tasa: "10%",
    condicion: "DEUDOR"
  },
  {
    id: 4,
    tipo_id: "CÉDULA JURÍDICA",
    no_identif: "3101787856",
    codigo_cleinte: "0",
    nombre_completo: "ALLAN BONILLA AGUILAR",
    tel_trab: "22213434",
    tel_cel: "88776655",
    email: "personal@gmail.com",
    riesgo_cumplimiento: "NA",
    score_atraso: "NA",
    rango_atraso: "61 A 90",
    dias_atraso_max: "70",
    prorrogas_aplicadas: "NA",
    nivel_riesgo: "NA",
    categoria_riesgo: "NA",
    gtia: "FIANZA",
    tipo_oper: "PERSONAL",
    saldo_credito: "₡7,200,500",
    cuota: "₡175,000",
    tasa: "20%",
    condicion: "DEUDOR"
  }
]