export const verificacion_normativa = [
  {
    programa: "SBP MICRO CRÉDITO",
    producto: "CAPITAL DE INVERSION",
    internos: {
      RIESGOS_DE_CUMPLIMIENTO: "NO TIENE",
      SCORE_DE_ATRASO: "NA",
      RANGO_DE_ATRASO: "1 a 30",
      DIAS_DE_ATRASO: "30",
      PRORROGAS_APLICADAS: "NA",
      NIVEL_DE_RIESGO: "NA",
      CATEGORIA_DE_RIESGO: "NA",
    },
    cic: {
      NIVEL_CHP: "1",
      PUNTAJE_CIC: "1.15",
      DIAS_ATRASO_EN_CIC: "30",
      NIVEL_CHP_SBD: "1",
      PUNTAJE_CIC_SBD: "1.15",
      DIAS_ATRASO_EN_CIC_SBD: "30",
      OPERACIONES_CON_ESTADO_1: "0",
      MESES_CONSULTADOS: "< = 12M",
    },
    buro: {
      Juicios_Act_Cantidad: "0",
      Juicios_Act_Monto: "0",
      Ref_Com_Cantidad: "0",
      Ref_Com_Monto: "0",
      Emb_B_Mueb_Cantidad: "0",
      Emb_B_Mueb_Monto: "0",
      Emb_B_InMueb_Cantidad: "0",
      Emb_B_InMueb_Monto: "0",
      Juicios_Hist_Cantidad: "0",
      Juicios_Hist_Monto: "0",
      Ref_Com_Hist_Cantidad: "0",
      Ref_Com_Hist_Monto: "0",
      Bienes_Prendados_Cantidad: "NA",
      Bienes_Prendados_Monto: "NA",
      Bienes_Hipotecados_Cantidad: "NA",
      Bienes_Hipotecados_Monto: "NA",
    },
    condiciones: {
      MONTO_MINIMO: "₡50.000",
      MONTO_MAXIMO: "₡29.000.000",
      MONEDA: "COLONES",
      TIPO_DE_CAMBIO: "568",
      TIPO_DE_TASA: "VARIABLE",
      FACTOR_FIJO_DE_TASA_DESCRIPCION: "TBP BCCR",
      FACTOR_FIJO_DE_TASA: "6.44%",
      FACTOR_VARIABLE_DE_TASA: "4.00%",
      TASA_TOTAL: "10.44%",
      PLAZO_MESES: "180",
      FPI_INT: "MENSUAL",
      FPP_PRINC: "MENSUAL",
      PLAN_INVERSION: "CAPITAL DE INVERSION",
      GARANTIA: "FIDUCIARIA",
    }
  },
  {
    programa: "FONADE SBD MICRO",
    producto: "CAPITAL DE TRABAJO",
    internos: {
      RIESGOS_DE_CUMPLIMIENTO: "NA",
      SCORE_DE_ATRASO: "NA",
      RANGO_DE_ATRASO: "31 a 60",
      DIAS_DE_ATRASO: "30",
      PRORROGAS_APLICADAS: "NA",
      NIVEL_DE_RIESGO: "NA",
      CATEGORIA_DE_RIESGO: "NA",
    },
    cic: {
      NIVEL_CHP: "1",
      PUNTAJE_CIC: "2.00",
      DIAS_ATRASO_EN_CIC: "60",
      NIVEL_CHP_SBD: "2",
      PUNTAJE_CIC_SBD: "2.00",
      DIAS_ATRASO_EN_CIC_SBD: "60",
      OPERACIONES_CON_ESTADO_1: ">=1",
      MESES_CONSULTADOS: "0",
    },
    buro: {
      Juicios_Act_Cantidad: "5",
      Juicios_Act_Monto: "₡75,000",
      Ref_Com_Cantidad: "5",
      Ref_Com_Monto: "₡75,000",
      Emb_B_Mueb_Cantidad: "1",
      Emb_B_Mueb_Monto: "₡5,000,000",
      Emb_B_InMueb_Cantidad: "1",
      Emb_B_InMueb_Monto: "₡25,000,000",
      Juicios_Hist_Cantidad: "5",
      Juicios_Hist_Monto: "₡75,000",
      Ref_Com_Hist_Cantidad: "5",
      Ref_Com_Hist_Monto: "₡75,000",
      Bienes_Prendados_Cantidad: "NA",
      Bienes_Prendados_Monto: "NA",
      Bienes_Hipotecados_Cantidad: "NA",
      Bienes_Hipotecados_Monto: "NA",
    },
    condiciones: {
      MONTO_MINIMO: "₡50.000",
      MONTO_MAXIMO: "₡1,000,000",
      MONEDA: "COLONES",
      TIPO_DE_CAMBIO: "568",
      TIPO_DE_TASA: "VARIABLE",
      FACTOR_FIJO_DE_TASA_DESCRIPCION: "TBP BCCR",
      FACTOR_FIJO_DE_TASA: "6.44%",
      FACTOR_VARIABLE_DE_TASA: "5.00%",
      TASA_TOTAL: "11.44%",
      PLAZO_MESES: "12",
      FPI_INT: "MENSUAL",
      FPP_PRINC: "AL VENCIMIENTO",
      PLAN_INVERSION: "CAPITA DE TRABAJO",
      GARANTIA: "FIDUCIARIA",
    }
  },
  {
    programa: "RECURSOS INTERNACIONALES",
    producto: "GASTOS DE VIAJE",
    internos: {
      RIESGOS_DE_CUMPLIMIENTO: "NA",
      SCORE_DE_ATRASO: "NA",
      RANGO_DE_ATRASO: "31 a 60",
      DIAS_DE_ATRASO: "30",
      PRORROGAS_APLICADAS: "NA",
      NIVEL_DE_RIESGO: "NA",
      CATEGORIA_DE_RIESGO: "NA",
    },
    cic: {
      NIVEL_CHP: "2",
      PUNTAJE_CIC: "2.00",
      DIAS_ATRASO_EN_CIC: "60",
      NIVEL_CHP_SBD: "2",
      PUNTAJE_CIC_SBD: "2.00",
      DIAS_ATRASO_EN_CIC_SBD: "60",
      OPERACIONES_CON_ESTADO_1: "> = 1",
      MESES_CONSULTADOS: "0",
    },
    buro: {
      Juicios_Act_Cantidad: "5",
      Juicios_Act_Monto: "387569",
      Ref_Com_Cantidad: "5",
      Ref_Com_Monto: "75000",
      Emb_B_Mueb_Cantidad: "1",
      Emb_B_Mueb_Monto: "5000000",
      Emb_B_InMueb_Cantidad: "1",
      Emb_B_InMueb_Monto: "25000000",
      Juicios_Hist_Cantidad: "5",
      Juicios_Hist_Monto: "75000",
      Ref_Com_Hist_Cantidad: "5",
      Ref_Com_Hist_Monto: "75000",
      Bienes_Prendados_Cantidad: "NA",
      Bienes_Prendados_Monto: "NA",
      Bienes_Hipotecados_Cantidad: "NA",
      Bienes_Hipotecados_Monto: "NA",
    },
    condiciones: {
      MONTO_MINIMO: "₡50.000",
      MONTO_MAXIMO: "₡15,000,000",
      MONEDA: "COLONES",
      TIPO_DE_CAMBIO: "568",
      TIPO_DE_TASA: "VARIABLE",
      FACTOR_FIJO_DE_TASA_DESCRIPCION: "TBP BCCR",
      FACTOR_FIJO_DE_TASA: "6.44%",
      FACTOR_VARIABLE_DE_TASA: "2.00%",
      TASA_TOTAL: "8.44%",
      PLAZO_MESES: "120",
      FPI_INT: "MENSUAL",
      FPP_PRINC: "MENSUAL",
      PLAN_INVERSION: "REFINANCIAMIENTO",
      GARANTIA: "FIDUCIARIA",
    }
  }
]

export const financiamiento = [
  {
    programa: "SBP MICRO CRÉDITO",
    producto: "REFINANCIAMIENTO",
    MONEDA: "COLONES",
    MONTO_MINIMO: "₡50000",
    MONTO_MAXIMO: "₡1000000",
    TIPO_DE_CAMBIO: "568",
    TIPO_DE_TASA: "VARIABLE",
    FACTOR_FIJO_DE_TASA_DESCRIPCION: "TBP BCCR",
    FACTOR_FIJO_DE_TASA: "6.44%",
    FACTOR_VARIABLE_DE_TASA: "4.00%",
    TASA_TOTAL: "10.44%",
    PLAZO_MESES: "180",
    FPI_INT: "MENSUAL",
    FPP_PRINC: "MENSUAL",
    PLAN_INVERSION: "Refinanciamiento Deudas",
    GARANTIA: "AUTOAVAL",
  },
  {
    programa: "FONADE SBD MICRO",
    producto: "REFINANCIAMIENTO C/F",
    MONEDA: "COLONES",
    MONTO_MINIMO: "₡100000",
    MONTO_MAXIMO: "₡5000000",
    TIPO_DE_CAMBIO: "568",
    TIPO_DE_TASA: "VARIABLE",
    FACTOR_FIJO_DE_TASA_DESCRIPCION: "TBP BCCR",
    FACTOR_FIJO_DE_TASA: "6.44%",
    FACTOR_VARIABLE_DE_TASA: "5.00%",
    TASA_TOTAL: "11.44%",
    PLAZO_MESES: "12",
    FPI_INT: "MENSUAL",
    FPP_PRINC: "AL VENCIMIENTO",
    PLAN_INVERSION: "Refinanciamiento Deudas",
    GARANTIA: "FIDUCIARIA",
  },
  {
    programa: "RECURSOS INTERNACIONALES",
    producto: "REFINANCIAMIENTO HIPOTECARIO",
    MONEDA: "COLONES",
    MONTO_MINIMO: "₡1000000",
    MONTO_MAXIMO: "₡15000000",
    TIPO_DE_CAMBIO: "568",
    TIPO_DE_TASA: "VARIABLE",
    FACTOR_FIJO_DE_TASA_DESCRIPCION: "TBP BCCR",
    FACTOR_FIJO_DE_TASA: "6.44%",
    FACTOR_VARIABLE_DE_TASA: "2.00%",
    TASA_TOTAL: "8.44%",
    PLAZO_MESES: "120",
    FPI_INT: "MENSUAL",
    FPP_PRINC: "MENSUAL",
    PLAN_INVERSION: "Refinanciamiento Deudas",
    GARANTIA: "HIPOTECARIA",
  }
]