export const CHANGE_CEDULA = "CHANGE_CEDULA";
export const CHANGE_STEP = "CHANGE_STEP";
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_FONT = "CHANGE_FONT";
export const CHANGE_SIZE = "CHANGE_SIZE";
export const CHANGE_STAT_SIZE = "CHANGE_STAT_SIZE";
export const CHANGE_ANIMATION = "CHANGE_ANIMATION";
export const CHANGE_FULLSCREEN = "CHANGE_FULLSCREEN";
export const CHANGE_MENU = "CHANGE_MENU";
export const CHANGE_STEP_FOUR = "CHANGE_STEP_FOUR";
export const CHANGE_RIESGO = "CHANGE_RIESGO";
export const CHANGE_PREELIMINAR = "CHANGE_PREELIMINAR";
export const CHANGE_CAPACIDAD = "CHANGE_CAPACIDAD";
export const CHANGE_ESTRUCTURA = "CHANGE_ESTRUCTURA";
export const CHANGE_GLOBAL = "CHANGE_GLOBAL";
export const CHANGE_SIZE_STEP = "CHANGE_SIZE_STEP";

export const CHANGE_USER = "CHANGE_USER";
